export const lab = {
  name: "SMILE Research Lab",
  expandedName: "Smart Movement for Innovative Learning Environment",
  affiliation: "Department of Educational Technology · Ewha Womans University",
  email: "jeongmin@ewha.ac.kr",
  address: "Education Building A, Room 530 · Seoul, Republic of Korea",
};

export const researchTracks = [
  {
    number: "01",
    shortTitle: "Individual Regulation",
    title: "Regulating learning in human–AI environments",
    questions: [
      "Metacognitive regulation",
      "Cognitive offloading",
      "Process-oriented learning analytics",
    ],
    tone: "teal",
  },
  {
    number: "02",
    shortTitle: "Socially Shared Regulation",
    title: "Designing for productive collaboration",
    questions: [
      "Collaborative regulation",
      "Conflict and dialogue support",
      "AI-supported group learning",
    ],
    tone: "sky",
  },
  {
    number: "03",
    shortTitle: "Inclusive Design",
    title: "Making participation possible for every learner",
    questions: [
      "Universal Design for Learning",
      "Teacher decision-making",
      "Ethical and culturally responsive AI",
    ],
    tone: "teal",
  },
];

export const publications = [
  {
    year: "2026",
    title: "교사교육에서 창의적 메타인지 촉진을 위한 LLM 기반 대화형 AI 에이전트 개발 연구",
    venue: "창의력교육연구, 26(1), 27–49",
    label: "AI + Metacognition",
    category: "korean",
  },
  {
    year: "2026",
    title: "대학생의 메타커뮤니케이션 역량 척도 개발 및 타당화",
    venue: "한국언론학보, 70(1), 230–262",
    label: "Social Regulation",
    category: "korean",
  },
  {
    year: "2025",
    title: "Generative AI chatbot for teachers' data-informed decision-making: Effects and insights",
    venue: "Educational Technology & Society, 28(3), 298–317",
    label: "SSCI",
    category: "international",
  },
  {
    year: "2025",
    title: "Personalized Support for Creative Problem Solving: Design and Development of a Generative AI Chatbot in Design Thinking",
    venue: "Educational Technology International, 26(1), 37–67",
    label: "Design Research",
    category: "international",
  },
  {
    year: "2025",
    title: "예비교원의 AI 디지털 교과서(AIDT) 활용 역량 진단도구 개발 및 타당화",
    venue: "교육공학연구, 41(3), 727–753",
    label: "Teacher Education",
    category: "korean",
  },
  {
    year: "2020",
    title: "Effects of robotics programming on the computational thinking and creativity of elementary school students",
    venue: "Educational Technology Research and Development, 68(1), 463–484",
    label: "SSCI",
    category: "international",
  },
];

export const awards = [
  {
    year: "2026",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "최우수상",
    recipients: "강연수 (M.A. student)",
    title: "Toulmin-Socratic Questioning 모델 기반 AI 읽기 튜터의 설계 및 적용: 비판적 읽기와 비판적 사고를 중심으로",
  },
  {
    year: "2025",
    event: "창의력교육학회 추계학술대회",
    type: "Paper · HMC Researcher Award",
    award: "우수상",
    recipients: "강다현 (M.A. student)",
    title: "교사교육을 위한 창의적 메타인지 촉진 LLM 기반 AI 에이전트 개발 연구",
  },
  {
    year: "2025",
    event: "AACE eLearn World Conference on EdTech",
    type: "Poster",
    award: "Outstanding Poster Award",
    recipients: "유다연 (M.A. student)",
    title: "Preparing Preservice Teachers to Address Social-Emotional Challenges in AI-Integrated Elementary Classrooms",
  },
  {
    year: "2025",
    event: "한국커뮤니케이션학회 봄철 정기학술대회",
    type: "Paper",
    award: "우수논문상",
    recipients: "황수민 (Ph.D. student)",
    title: "대학생의 메타커뮤니케이션 역량 측정을 위한 척도 개발",
  },
  {
    year: "2025",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "우수상",
    recipients: "강다현 (M.A. student)",
    title: "AI 디지털교과서 수업 적용을 위한 예비교원 실천역량 진단도구 개발",
  },
  {
    year: "2025",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Poster",
    award: "최우수상",
    recipients: "유다연 (M.A. student)",
    title: "초등 AI 디지털 활용 교육에서 사회정서적 문제 대응을 위한 예비교사 양성 프로그램 개발 연구",
  },
  {
    year: "2024",
    event: "한국교육정보미디어학회·한국교육공학회 추계공동학술대회",
    type: "Paper",
    award: "우수 논문상",
    recipients: "유다연 (M.A. student)",
    title: "디지털 활용 교육에서 사회정서적 지원을 위한 교육설계원리 개발연구",
  },
  {
    year: "2024",
    event: "창의력교육학회 추계학술대회",
    type: "HMC Researcher Award",
    award: "우수상",
    recipients: "손예지 (M.A. student)",
    title: "비형식학습에서 디자인 씽킹을 지원하는 생성형 AI 챗봇 개발 연구",
  },
  {
    year: "2024",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "장려상",
    recipients: "추가연, 권나영, 이다은, 장서연 (B.A. students)",
    title: "약물남용 예방교육을 위한 생성형 AI 기반 롤플레잉 수업 설계와 효과성 연구",
  },
  {
    year: "2024",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "장려상",
    recipients: "손예지, 강지윤, 이예은 (M.A. students)",
    title: "대학 튜터링 프로그램에서 튜터 지원을 위한 생성형 AI 챗봇 개발",
  },
  {
    year: "2024",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "장려상",
    recipients: "이화연, 홍연후, 유다연 (M.A. students)",
    title: "국내 교육에서의 윤리적AI 활용 연구 동향",
  },
  {
    year: "2024",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Poster",
    award: "금상",
    recipients: "정서희, 김결이, 김영은, 김윤겸, 이은빈 (B.A. students)",
    title: "생태실천교육을 위한 자연사박물관의 전시 커뮤니케이션 방법 연구",
  },
  {
    year: "2023",
    event: "한국교육정보미디어학회·한국교육공학회 추계공동학술대회",
    type: "Paper",
    award: "최우수 논문상",
    recipients: "이지원 (M.A. student)",
    title: "ChatGPT 기반 학습 맥락에서 대화형 AI 프롬프트 설계 지침 탐색: 프롬프트 엔지니어링 기법을 중심으로",
  },
  {
    year: "2023",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "차세대 연구자상 우수상",
    recipients: "김진솔 (Ph.D. student)",
    title: "MOOC 에서 자동 텍스트 분석 기법을 활용한 인지적 실재감 분석",
  },
  {
    year: "2023",
    event: "한국교육공학회 춘계학술대회",
    type: "Poster",
    award: "우수 포스터 발표상",
    recipients: "석희진, 이지원, 강지윤 (M.A. students)",
    title: "예비 교수의 교육 데이터 리터러시 프레임 워크 개발 연구",
  },
  {
    year: "2023",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Paper",
    award: "우수 논문상",
    recipients: "황수민 (Ph.D. student)",
    title: "온라인 수업 환경에서 초등학생의 의사소통 역량 개발을 위한 구성요인 탐색",
  },
  {
    year: "2023",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Paper",
    award: "최우수 논문상",
    recipients: "이지원 (M.A. student), 홍지혜 (Integrated M.A.–Ph.D. student)",
    title: "중학생의 디지털 시민성 향상을 위한 M(Metaverse) - PBL수업 개발 연구",
  },
  {
    year: "2021",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Paper",
    award: "우수 논문상",
    recipients: "박가영 (M.A. student)",
    title: "대학 신입생 대상 온라인 튜터링에 참여한 튜티의 경험탐색",
  },
  {
    year: "2021",
    event: "발명교육 분야 신진 연구과제 공모전",
    type: "Research Competition",
    award: "공모선정",
    recipients: "허미선 (Integrated M.A.–Ph.D. student)",
    title: "국내 발명교육 효과에 관한 메타분석",
  },
  {
    year: "2019",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Poster",
    award: "우수 논문상",
    recipients: "하석영, 김진솔 (M.A. students)",
    title: "대학생 창의성 교육 연구동향",
  },
  {
    year: "2018",
    event: "한국교육정보미디어학회·한국교육공학회 추계공동학술대회",
    type: "Dissertation",
    award: "우수박사학위논문상",
    recipients: "조보람 (Ph.D.)",
    title: "메타분석을 통한 플립러닝의 효과검증",
  },
  {
    year: "2018",
    event: "한국교육정보미디어학회 춘계학술대회",
    type: "Poster",
    award: "최우수상",
    recipients: "정하연 (M.A. student)",
    title: "대학 팀 프로젝트 학습에서 과업갈등, 다양성 수용도와 팀 몰입 및 성취도의 관계에서 관계갈등의 매개 효과",
  },
];

export const newsItems = [
  {
    year: "2026",
    category: "Perspective",
    title: "Reclaiming judgment in the age of generative AI",
    originalTitle:
      "AI에게 맡긴 사고, 다시 되찾아야 할 판단 — 생성형 AI 시대 대학 교육의 과제",
    description:
      "In a new essay for University Press In&Out, Jeongmin Lee reflects on how generative AI is reshaping student writing and why higher education must help learners retain ownership of judgment and thought.",
    url: "https://www.unipress.co.kr/news/articleView.html?idxno=14682",
  },
  {
    year: "2026",
    category: "Publication",
    title: "New study on an LLM-based conversational AI agent for creative metacognition",
    description:
      "The study develops a conversational agent designed to foster creative metacognition in teacher education.",
  },
  {
    year: "2026",
    category: "Publication",
    title: "Meta-communication competency scale published",
    description:
      "Our new scale development and validation study examines university students’ meta-communication competency.",
  },
  {
    year: "2025",
    category: "International journal",
    title: "Generative AI for teachers’ data-informed decision-making",
    description:
      "Our research on a generative AI chatbot for teacher decision-making was published in Educational Technology & Society.",
  },
];

export const team = {
  director: {
    name: "Jeongmin Lee",
    degree: "Ph.D.",
    role: "Professor, Department of Educational Technology",
    institution: "Ewha Womans University",
    initials: "JL",
  },
  currentMembers: [
    { name: "강연수", initials: "YS" },
    { name: "김영지", initials: "YJ" },
    { name: "안소정", initials: "SJ" },
    { name: "유난희", initials: "NH" },
    { name: "장서윤", initials: "SY" },
    { name: "박혜민", initials: "HM" },
    { name: "하석영", initials: "SY" },
    { name: "Klishch, Nataliia", initials: "NK" },
  ],
  doctoralCandidates: [
    { name: "김소망", initials: "SM" },
    { name: "김진솔", initials: "JS" },
    { name: "남선혜", initials: "SH" },
    { name: "배윤주", initials: "YJ" },
    { name: "허미선", initials: "MS" },
    { name: "홍지혜", initials: "JH" },
    { name: "황수민", initials: "SM" },
  ],
  alumni: {
    phd: [
      {
        name: "고은지",
        affiliation: "Research Professor / Lecturer, Ewha Womans University",
      },
      {
        name: "노지예",
        affiliation: "Professor, Duksung Women’s University",
      },
      {
        name: "이명화",
        affiliation: "Researcher / Lecturer, Kangnam University",
      },
      {
        name: "조보람",
        affiliation: "Professor, Kyungsung University",
      },
    ],
    masters: [
      {
        name: "ALTON, HAMIDE KUBRA",
        affiliation: "Professor, Namseoul University",
      },
      {
        name: "정연지",
        affiliation: "Professor, Texas A&M University",
      },
      { name: "박가영", affiliation: "NAVER" },
      { name: "석희진", affiliation: "LG CNS" },
      {
        name: "박새록",
        affiliation: "Ph.D. Student, University of North Carolina at Chapel Hill",
      },
      {
        name: "손예지",
        affiliation: "Ph.D. Student, University of Florida",
      },
      {
        name: "이예은",
        affiliation: "Ph.D. Student, Florida State University",
      },
      {
        name: "이지원",
        affiliation: "Ph.D. Student, North Carolina State University",
      },
      { name: "CHENG, PANNA" },
      { name: "강다현" },
      { name: "김영화" },
      { name: "문지윤" },
      { name: "박현경" },
      { name: "오보라" },
      { name: "오성은" },
      { name: "유다연" },
      { name: "이화연" },
      { name: "전정아" },
      { name: "정현민" },
      { name: "정연화" },
      { name: "정하연" },
      { name: "홍연후" },
    ],
  },
};
